#186 Mediaserver for Cooper
vanmxpx/ISDPlatform pull request #192
Opened 2019-08-15 22:48 UTC by emptycoder

2019-08-19 21:21 UTC, horba commented on Cooper/ClientApp/src.v2/app/components/upload-form/upload-form.component.ts
> +              private mediaserver: MediaserverService) { }
no business logic in dummy service, all interactions via @Input() and @Output()

2019-08-20 11:25 UTC, Hunroll requested changes

2019-08-20 11:25 UTC, Hunroll commented on Cooper.Services.Interfaces/Cooper.Services.Interfaces.csproj
> +      <HintPath>..\..\..\..\..\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.http.features\2.2.0\lib\netstandard2.0\Microsoft.AspNetCore.Http.Features.dll</HintPath>
Nuget: 
![image](https://user-images.githubusercontent.com/3989323/63343107-df72f400-c355-11e9-87e6-4432e0d14cf2.png)

2019-08-29 09:58 UTC, horba commented on Cooper/ClientApp/src.v2/app/components/upload-form/upload-form.component.ts
> +  @Input() public error: string;
error-message

2019-08-29 09:58 UTC, horba commented on Cooper/ClientApp/src.v2/app/components/upload-form/upload-form.component.ts
> +  @Output() public upload: EventEmitter<any> = new EventEmitter();
let's decide with team about common naming of custom events :)

2019-08-31 08:18 UTC, Hunroll approved these changes

2019-09-07 21:55 UTC, horba commented on Cooper/ClientApp/src.v2/app/components/upload-form/upload-form.component.scss
> +      background: #48494c
;

2019-09-07 21:56 UTC, horba approved these changes
after ; fix can be merges

2019-09-07 21:57 UTC, horba approved these changes

2019-09-07 22:16 UTC, merged